title:              Nulová pozice
email:              nulovapozice@gmail.com
description:        Propojování kultury a umění s jinými oblastmi života.
description_long:   Náplní spolku je propojování kultury a umění s jinými oblastmi života; integrace různých skupin obyvatel do společnosti prostřednictvím kultury a umění; vytvoření platformy pro setkávání umělců a zástupců kulturních organizací.
author:             Nulová pozice
baseurl:            ""
url:                "https://nulovapozice.github.io"

# Social Profiles
twitter_username:
github_username:    nulovapozice
facebook_username:  nulovapozice
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

exclude:
  - "/vendor/"
  - bundle
  - CNAME
  - docker-compose.yaml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - README*.md
  - .*
  - .idea/
  - .git/
